esphome:
  name: sauna
  platform: ESP32
  board: nodemcu-32s

substitutions:
  <<: !include sauna.secrets

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  # manual_ip:
    # static_ip: 192.168.88.10
    # subnet: 255.255.240.0
    # gateway: 192.168.88.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
  #  ssid: "nasa"
  #  password: "12345678"

captive_portal:


web_server:
  port: 80

  # Enable logging
logger:


#ota:

# http://sauna.local/sensor/living_room_brightness

# xiaomi_ble:
esp32_ble_tracker:

dallas:
  - pin: GPIO18

sensor:

  - platform: dallas
    address: 0x6A800000262BC928
    name: "Bak 1 Temp"

  - platform: adc
    pin: GPIO32
    name: "Bak 1 Level"
    update_interval: 60s
    filters:
      - lambda: return (x / 1024 - 0.04) / 0.018 / 0.5;
    unit_of_measurement: "cm"
    accuracy_decimals: 1
    
# > system_profiler SPBluetoothDataType
# http://sauna.local/sensor/lywsd03mmc_temperature
  - platform: atc_mithermometer
  # platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:0C:16:65"
    # bindkey: "60e7d1ee4bfe2ffc388dad808e00d422"
    temperature:
      name: "LYWSD03MMC Temperature"
    humidity:
      name: "LYWSD03MMC Humidity"
    battery_level:
      name: "LYWSD03MMC Battery Level"

