esphome:
  name: sauna
  platform: ESP32
  board: nodemcu-32s

substitutions:
  <<: !include sauna.secrets

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "sauna"
  #   password: "12345678"

ota:
  safe_mode: true
  password: 12345678

# captive_portal:

mqtt:
  broker: broker.hivemq.com
  port: 1883
  username: sauna
  password: sauna


web_server:
  port: 80
  # css_include: "webserver-v1.min.css"
  css_include: "sauna.css"
  css_url: ""
  # js_include: "webserver-v1.min.js"
  js_include: "sauna.js"
  js_url: ""

# Enable logging
logger:
  level: DEBUG


esp32_ble_tracker:

dallas:
  - pin: GPIO18

sensor:

  - platform: dallas
    address: 0xEF800000263C0828
    name: "Bak 1 Temp"
 
  - platform: dallas
    address: 0x6A800000262BC928
    name: "Bak 2 Temp"

  - platform: adc
    pin: GPIO32
    name: "Bak 1 Level"
    update_interval: 60s
    filters:
      # - lambda: return (x / 1024 - 0.04) / 0.018 / 0.5;
      - calibrate_linear:
        - 0.37 -> 0.0
        - 0.64 -> 11.0
    unit_of_measurement: "cm"
    accuracy_decimals: 1

  - platform: adc
    pin: GPIO33
    name: "Bak 2 Level"
    update_interval: 60s
    filters:
      - calibrate_linear:
        - 0.37 -> 0.0
        - 0.64 -> 11.0
    unit_of_measurement: "cm"
    accuracy_decimals: 1

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:0C:16:65"
    temperature:
      name: "Room 1 Temperature"
    humidity:
      name: "Room 1 Humidity"
    battery_level:
      name: "Room 1 Battery"

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:26:D7:AF"
    temperature:
      name: "Room 2 Temperature"
    humidity:
      name: "Room 2 Humidity"
    battery_level:
      name: "Room 2 Battery"

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:B2:E7:04"
    temperature:
      name: "Room 3 Temperature"
    humidity:
      name: "Room 3 Humidity"
    battery_level:
      name: "Room 3 Battery"

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:7B:73:84"
    temperature:
      name: "Room 4 Temperature"
    humidity:
      name: "Room 4 Humidity"
    battery_level:
      name: "Room 4 Battery"
  
