esphome:
  name: sauna
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "zhopa"
  password: "melnikov"
  # manual_ip:
    # static_ip: 192.168.88.10
    # subnet: 255.255.240.0
    # gateway: 192.168.88.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
  #  ssid: "nasa"
  #  password: "12345678"

captive_portal:


web_server:
  port: 80

  # Enable logging
logger:


#ota:

# http://sauna.local/sensor/living_room_brightness

xiaomi_ble:
esp32_ble_tracker:

sensor:

  - platform: adc
    pin: A0
    name: "Living Room Brightness"
    update_interval: 60s
    
# > system_profiler SPBluetoothDataType
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:0C:16:65"
    bindkey: "60e7d1ee4bfe2ffc388dad808e00d422"
    temperature:
      name: "LYWSD03MMC Temperature"
    humidity:
      name: "LYWSD03MMC Humidity"
    battery_level:
      name: "LYWSD03MMC Battery Level"

